apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "whatsapp-monitor.fullname" . }}-config
  labels:
    {{- include "whatsapp-monitor.labels" . | nindent 4 }}
data:
  WHATSAPP_GROUP_NAME: {{ .Values.monitor.config.groupName | quote }}
  KAFKA_BROKERS:       "{{ include "whatsapp-monitor.fullname" . }}-kafka:9092"
  KAFKA_SCORE_TOPIC:   {{ .Values.monitor.config.scoreTopicName | quote }}
  KAFKA_POLL_TOPIC:    {{ .Values.monitor.config.pollTopicName | quote }}
  POSTGRES_HOST:       "{{ include "whatsapp-monitor.fullname" . }}-postgres"
  POSTGRES_PORT:       "5432"
  POSTGRES_DB:         {{ .Values.postgres.database | quote }}
  POSTGRES_USER:       {{ .Values.postgres.user | quote }}
  AUTH_DIR:            {{ .Values.monitor.config.authDir | quote }}
