apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "whatsapp-monitor.fullname" . }}-postgres-data
  labels:
    {{- include "whatsapp-monitor.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}
  storageClassName: {{ .Values.postgres.storageClass }}
