apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "whatsapp-monitor.fullname" . }}-credentials
  labels:
    {{- include "whatsapp-monitor.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.monitor.credentials.storage }}
  storageClassName: {{ .Values.monitor.credentials.storageClass }}
