apiVersion: v1
kind: Service
metadata:
  name: {{ include "whatsapp-monitor.fullname" . }}-zookeeper
  labels:
    {{- include "whatsapp-monitor.labels" . | nindent 4 }}
spec:
  selector:
    app: zookeeper
  ports:
    - port: {{ .Values.zookeeper.clientPort }}
      targetPort: {{ .Values.zookeeper.clientPort }}
