apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "whatsapp-monitor.fullname" . }}-zookeeper
  labels:
    {{- include "whatsapp-monitor.labels" . | nindent 4 }}
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: {{ .Values.zookeeper.image }}
          ports:
            - containerPort: {{ .Values.zookeeper.clientPort }}
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "{{ .Values.zookeeper.clientPort }}"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
